name: Security Scans
on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 1 * * 1"
jobs:
  sast_sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Bandit
        run: bandit -r src -f txt -o bandit.txt
      - name: pip-audit
        run: pip-audit -r requirements.txt --strict --progress-spinner off
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.txt